### ISSUE TITLE
Allow speakers to see their own talk

### ISSUE THREAD

**Issue by DavidJFelix** [pyohio/pyohio#41]
I can't see my own talk # 277. I assume this is to keep me from seeing reviews and placing a review against my own talk. It's confusing if this is the case or for some reason it's not appearing for anyone.

**Comment by CarlFK** [comment]
It is so you can't review/vote on your own talk.

This question comes up now and then.  The only good fix I can think of is
showing it but disabling the UI, which sounds tedious.

On Sat, Jun 13, 2015 at 11:04 AM, David J. Felix <notifications@github.com>
wrote:

> I can't see my own talk # 277. I assume this is to keep me from seeing
> reviews and placing a review against my own talk. It's confusing if this is
> the case or for some reason it's not appearing for anyone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyohio/pyohio/issues/41>.
>



-- 
Carl K

**Comment by DavidJFelix** [comment]
I figured as much. I was told to post a bug here about it. I'll live, but it wasn't clear to me on my dashboard. Maybe a blurb that says "your proposals will not appear for you in the reviewing process". Not a huge issue.

**Comment by efloehr** [comment]
I'm going to reopen this issue because as David said, it would be good to, in the code, when reviewing talks to note that the reviewer's talk doesn't show up, or something. Explicit better than implicit and all that.

**Comment by DavidJFelix** [comment]
I'm going to re-close this because I don't intend to follow or contribute to the progress of this ticket
