### ISSUE TITLE
pyohio.org does not use HTTPS

### ISSUE THREAD

**Issue by dowski** [pyohio/pyohio#63]
Chrome and other browsers (rightly) warn users not to enter passwords on the PyOhio sign-in page. This might discourage users from signing in to e.g. submit a talk proposal.

**Comment by tylerdave** [comment]
Agreed! I just set up a Let's Encrypt cert on slack.pyohio.org and that wasn't too hard. @efloehr you know what it would take to get that set up w/ our web hosting?

**Comment by Rorosha** [comment]
That's exactly why I didn't create an account. But I'm glad to find that an issue has already been filed!

**Comment by efloehr** [comment]
Thanks for the report!

pyohio.org is now set up for HTTPS, via Let's Encrypt, and HTTP will redirect to HTTPS.
